### PR TITLE
Dependency is updated to latest

### PR DESCRIPTION
**Pull request by darkmatter18**
The update is the same as #21 
But in a more organized way.
Hope for the best 😃

### CODE REVIEW

**Comment by mroderick** [comment]
Nice! Thank you for sticking with it!

**Comment by mroderick** [comment]
This PR looks good to me

**Review by mroderick — APPROVED** [review]

**Comment by darkmatter18** [comment]
> This PR looks good to me

Thanks a lot. When the PR will be marged?

**Comment by gboer** [comment]
@mroderick does anything else need to happen to get this PR merged? :)

**Comment by KristjanESPERANTO** [comment]
@isaacs
Apparently @coreyfarrell hasn't been active on GitHub for a while, can you please merge this?

**Comment by mroderick** [comment]
> @mroderick does anything else need to happen to get this PR merged? :)

I don't know. I'm not a maintainer of this package, I just reviewed the work done, hoping to get it merged :)

**Comment by fyzhu** [comment]
@bcoe Could we merge this, this warning affected a lot of people.

**Comment by CPLepage** [comment]
@isaacs @coreyfarrell Any updates on when this could be merged in ?

**Pull request closed without merging**
