### PR TITLE
chore: Remove package-lock.json

### PR DESCRIPTION
**Pull request by coreyfarrell**

### CODE REVIEW

**Comment by JaKXz** [comment]
Apologies for missing the discussion on this, but why is this a trending thing?

**Comment by coreyfarrell** [comment]
I'm not sure there was a real discussion on it, I didn't merge this without feedback even though it's a simple change as I don't want to ignore the possibility that others disagree with me on this.

Personally I do not see value in package-lock files for libraries.  It inflates diff's, causes merge conflicts, and most importantly blocks CI from automatically testing in-range updates of dependencies (including deep dependencies).  Yes if we enable greenkeeper we get automatic testing of direct dependencies and anything they explicitly upgrade, but we rarely test deep dependencies because the package-lock holds us back.  Even for direct dependencies with greenkeeper enabled we only test the updated version once.  For an in-range update greenkeeper does not create a PR for the update, so the package-lock in master remains pointed to the old version of everything.  I find myself frequently deleting the package-lock.json to regenerate so that travis tests against current packages.  Even for applications like nyc the package-lock is not published to npm so all it really does (IMV) is hold back dependencies used by CI.

I sometimes have trouble gauging how people will view my tone.  I hope this post does not come across too aggressive, I do have a pretty strong opinion against the package-lock but I'm very open to opposing opinion.  Any help understanding specific benefits of having the package-lock would be very much appreciated.  CC @bcoe @isaacs (please feel free to tag others who might belong in this discussion).

**Comment by bcoe** [comment]
@coreyfarrell I've gotten used to using a `package-lock.json`, because I've found it makes it a little easier for me to isolate which dependency broke a project during an upgrade.

No super strong opinion though, do what you think is best.

**Comment by isaacs** [comment]
Sorry, I saw this late.

I don't think that going without a package-lock.json is a good idea, for libraries or apps.

You don't need to remove `package-lock.json` to update deps.  Running `npm update` will do that (and update the package-lock.json), and it's much faster than having to re-build the tree each time.

Tests against deep dependencies in CI don't happen without pushing additional commits or manually triggering a build, and not using a package-lock means that npm audit doesn't function properly.  If that's something you want to have happen, though, it's easy enough to have `npm update` run as a setup script in .travis.yml.

Not having a package-lock.json means that Travis can't run `npm ci`, which results in significantly faster builds when there's no existing node_modules folder, but this feature relies on package-lock.json.

In the future, I expect that the package-lock.json will become a _more_ load-bearing feature within npm, rather than less.  (Though, it is ephemeral, since it will be regenerated if it's deleted.)

All in all, I see little benefit to this, and most of those benefits can be had in better ways.

**Comment by coreyfarrell** [comment]
I just tried running `npm update` on nyc, it did not update tap to 12.7.0 (package.json has `^12.6.5`).  I ran `npm update` a second time and then it updated tap to 12.7.0, but it also changed the package.json range.  `npm --depth 9999 update` did the same thing.

**Comment by isaacs** [comment]
Using npm 6.9.0, I see that it updates on the first pass, so I'm not sure why it wasn't doing that on your system.  Updating package.json is by design. (An update is an install.  You can run it with `--no-save` to prevent this, but `--save` has been the default for a while now.)

One more issue: given the deduplication that npm does, there's no assurance that a library being used "in the wild" will necessarily be pulling the latest versions of its dependencies.  It'll get the optimized intersection of all the dependency ranges for that module, which may or may not be the latest release.

**Comment by coreyfarrell** [comment]
```sh
git clone https://github.com/istanbuljs/nyc
cd nyc
npm --depth 9999 update
```
This updates package-lock.json but not package.json, it installs tap@12.6.5.  Running `npm --depth 9999 update` a second time updates tap to 12.7.0 (with corresponding changes to package.json and package-lock.json).

**Comment by isaacs** [comment]
Oh, interesting.  That feels like an npm bug to me.  I wasn't testing it with an empty node_modules folder, that could be the problem.  (I'm not sure what the `--depth 9999` would be doing here?  It's a top level dep you're updating, after all.)

**Comment by coreyfarrell** [comment]
I doubt `--depth 9999` has any effect on this specifically, just mentioned it because that's what I used.  `npm help update` says that deep dependencies are not updated without this.  Side note `npm help update` is a bit wonky on my system, looks like some kind of markdown to man conversion error.

**Pull request merged**
